### ISSUE TITLE
Set up Tornado server

### ISSUE THREAD

**Issue by MartinAltmayer** [MartinAltmayer/pokerserver#1]
Create a working executable file to start the server.

**Comment by MartinAltmayer** [comment]
Read parameters from command line (argparse).

Supported parameters (with defaults):
freeTables: 10  # make sure to always provide this amount of free tables
startBalance: 40 # amount of money when joining a table
minPlayerCount: 4 # match starts when this number of players is reached
maxPlayerCount: 8 # maximum number of players that can be present at a table at any timepoint
smallBlind: 1
bigBlind: 2
answerTimeout: 0.5s # active client must answer before this timeout is reached or he will be kicked
turnInterval: 2s # specifies how long to wait after a client answered before the next client's turn starts (allows to display a bot match).

**Comment by AndreasMalecki** [comment]
More parameters: ip address and port to use.
