### ISSUE TITLE
Create empty tables

### ISSUE THREAD

**Issue by MartinAltmayer** [MartinAltmayer/pokerserver#13]
Make sure always `freeTables` (from command line options) tables that have not been started yet are available.

**Comment by MartinAltmayer** [comment]
Since https://github.com/MartinAltmayer/pokerserver/commit/68597963a3c7fa1bcda15b718260b6cf2956fdfc empty tables are created at server startup. We still need a check when a table is closed.

**Comment by AndreasMalecki** [comment]
We need to reopen new tables.
