### ISSUE TITLE
Set up RabbitMQ

### ISSUE THREAD

**Issue by MartinAltmayer** [MartinAltmayer/pokerserver#14]
We need one public channel per table and one private channel per table and joined player.

**Comment by AndreasMalecki** [comment]
After some research, I would say that RabbitMQ is a bit too complex for our purpose and I do not see an easy way to securely separate channels. We could use it as a simple trigger making each client load the current table state via our web interface. However, as we already use asyncio, I would propose creating a TCP server using BaseEventLoop.create_server with a simple custom protocol instead. The protocol would consist of an initial authentication step using the uuid we provide when taking a seat at a table and publication of the current table states afterwards. What do you think?

**Comment by AndreasMalecki** [comment]
I think, I will compare a RabbitMQ client/server setup to a solution using asyncio. On the client side we could postpone explaining async + await by giving the audience something like https://docs.python.org/3.5/library/asyncio-protocol.html#tcp-echo-client-protocol as an example.
