### ISSUE TITLE
Create /stats route

### ISSUE THREAD

**Issue by MartinAltmayer** [MartinAltmayer/pokerserver#16]
`{<playerName>: {matches: x, buyIn: y, gain: z}}`
where
matches is the number of tables where the player participated (only tables that have actually started).
buyIn is the total amount of money the player got at the beginning of all of his tables
gain is the total amount of money the player had at the end of all of his tables

**Comment by MartinAltmayer** [comment]
`{<playerName>: {matches: x, buyIn: y, gain: z}}`
where
matches is the number of tables where the player participated (only tables that have actually started).
buyIn is the total amount of money the player got at the beginning of all of his tables
gain is the total amount of money the player had at the end of all of his tables

**Comment by AndreasMalecki** [comment]
I changed the URI to /statistics.
