### ISSUE TITLE
Ensure that a table cannot be modified while an action is processed during a match 

### ISSUE THREAD

**Issue by AndreasMalecki** [MartinAltmayer/pokerserver#33]
I feel that it might be possible for the current player to corrupt the state of a table by sending multiple valid requests at the same time. We should ensure that operations on a table are atomic.

**Comment by MartinAltmayer** [comment]
Each player action route (/fold etc.) will call check_and_unset_current_player before modifying the table. This function is specifically constructed to make sure it is called only once per turn.

**Comment by AndreasMalecki** [comment]
Okay. I just wanted to look at this again. Closing this issue.
