### ISSUE TITLE
Create database abstraction layer and stats table

### ISSUE THREAD

**Issue by MartinAltmayer** [MartinAltmayer/pokerserver#4]
Use SQLite3 with e.g. https://github.com/aio-libs/aioodbc
Create stats table and methods with the necessary queries to access it.

**Comment by MartinAltmayer** [comment]
There never has been a more complicated setup to get a simple SQLite database running ;-)

**Comment by AndreasMalecki** [comment]
;-) If you know exactly what to do, it is not that complicated...

**Comment by MartinAltmayer** [comment]
Our own database abstraction layer uses aioodbc which sits on top of pyodbc which uses the actual odbc with the sqliteodbc driver. It's particularly annoying because Python comes with a decent SQLite module builtin. I'd like to write an async module that directly uses the builtin module. But don't worry, not before the pokerserver is finished ;-)
